version: '3'

services:
    mysql:
        image: mariadb
        container_name: Server_MariaDB
        env_file: ./env/.env
        environment:
            MYSQL_DATABASE: login
            MYSQL_USER: infra
            MYSQL_PASSWORD: Ricoh+123
            MYSQL_ROOT_PASSWORD: Oracle+2104
        restart: always
        volumes:
          - ./bases:/var/lib/mysql
    phpmyadmin:
        container_name: MyPhpmyadmin
        depends_on:
          - mysql
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - "7880:80"
        env_file: ./env/.env
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: Oracle+2104
    nodejs:
      container_name: nodejs
      image: emanuel/erivero
      restart: always
      ports:
        - "3000:3000"
      depends_on:
        - mysql 