on: push
name: deploy
jobs:
  deploy:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.PLANTA_USERNAME }}
        password: ${{ secrets.PLANTA_PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "routes/*"
        target: "/home/erivero/Escritorio/creandogit"